#property copyright "Generated by GPT-5.3 Codex"
#property version   "1.01"
#property strict

#include <Trade/Trade.mqh>

enum BiasDirection
  {
   BIAS_NONE = 0,
   BIAS_BULL = 1,
   BIAS_BEAR = -1
  };

input string          InpSymbol                 = "";
input long            InpMagicNumber            = 4620;
input ENUM_TIMEFRAMES InpHTF                    = PERIOD_H4;
input ENUM_TIMEFRAMES InpLTF                    = PERIOD_M15;
input int             InpHTFLookbackBars        = 500;
input int             InpLTFLookbackBars        = 350;
input int             InpOrderBlockSearchBars   = 30;
input int             InpPatternLookbackBars    = 140;
input int             InpMaxSweepToBreakBars    = 12;
input double          InpRiskPercent            = 0.50;
input double          InpRewardRisk             = 2.00;
input int             InpBreakBufferPoints      = 20;
input int             InpSweepBufferPoints      = 15;
input int             InpStopBufferPoints       = 25;
input int             InpMaxSpreadPoints        = 0;
input int             InpMaxSlippagePoints      = 25;
input bool            InpRequireSweepInsideOB   = true;
input bool            InpUseSessionFilter       = false;
input int             InpSessionStartHour       = 6;
input int             InpSessionEndHour         = 22;
input int             InpMaxTradesPerDay        = 0;
input double          InpMaxDailyLossPercent    = 0.0;
input bool            InpAllowSinglePositionOnly= true;
input double          InpBreakEvenAtR           = 1.0;
input int             InpBreakEvenLockPoints    = 10;

struct HTFContext
  {
   int      direction;
   int      breakIndex;
   int      pivotIndex;
   int      rangeAnchorIndex;
   int      orderBlockIndex;
   double   rangeLow;
   double   rangeHigh;
   double   midpoint;
   double   obLow;
   double   obHigh;
   datetime snapshotTime;
  };

struct EntrySignal
  {
   bool     valid;
   int      direction;
   int      swingIndex;
   int      sweepIndex;
   double   referenceLevel;
   double   stopPrice;
   datetime signalTime;
  };

CTrade   g_trade;
datetime g_lastProcessedLTFBar = 0;
datetime g_lastExecutedSignal  = 0;
string   g_tradeSymbol         = "";

double SymbolPointValue()
  {
   return SymbolInfoDouble(g_tradeSymbol,SYMBOL_POINT);
  }

int SymbolDigitsValue()
  {
   return (int)SymbolInfoInteger(g_tradeSymbol,SYMBOL_DIGITS);
  }

double NormalizePrice(const double price)
  {
   return NormalizeDouble(price,SymbolDigitsValue());
  }

void PushIndex(int &arr[],const int value)
  {
   const int n=ArraySize(arr);
   ArrayResize(arr,n+1);
   arr[n]=value;
  }

bool IsSwingHigh(const MqlRates &rates[],const int i)
  {
   const int n=ArraySize(rates);
   if(i<=0 || i>=n-1)
      return false;
   return (rates[i].high>rates[i-1].high && rates[i].high>rates[i+1].high);
  }

bool IsSwingLow(const MqlRates &rates[],const int i)
  {
   const int n=ArraySize(rates);
   if(i<=0 || i>=n-1)
      return false;
   return (rates[i].low<rates[i-1].low && rates[i].low<rates[i+1].low);
  }

int FindLatestIndexBefore(const int &indices[],const int pivot)
  {
   for(int i=ArraySize(indices)-1;i>=0;--i)
     {
      if(indices[i]<pivot)
         return indices[i];
     }
   return -1;
  }

void CollectSwings(const MqlRates &rates[],const int startIndex,const int endIndex,int &swingHighs[],int &swingLows[])
  {
   ArrayResize(swingHighs,0);
   ArrayResize(swingLows,0);

   for(int i=startIndex;i<=endIndex;i++)
     {
      if(IsSwingHigh(rates,i))
         PushIndex(swingHighs,i);
      if(IsSwingLow(rates,i))
         PushIndex(swingLows,i);
     }
  }

bool LoadRates(const ENUM_TIMEFRAMES timeframe,const int bars,MqlRates &rates[])
  {
   ArraySetAsSeries(rates,false);
   const int copied=CopyRates(g_tradeSymbol,timeframe,0,bars,rates);
   if(copied<=0)
      return false;
   return (copied>=30);
  }

bool CandleTouchesZone(const MqlRates &bar,const double zoneLow,const double zoneHigh)
  {
   if(zoneHigh<zoneLow)
      return false;
   return (bar.low<=zoneHigh && bar.high>=zoneLow);
  }

bool FindBullishContext(const MqlRates &rates[],const int lastClosed,const int &swingHighs[],const int &swingLows[],HTFContext &ctx)
  {
   const double point=SymbolPointValue();
   const double breakBuffer=InpBreakBufferPoints*point;

   for(int h=ArraySize(swingHighs)-1;h>=0;--h)
     {
      const int swingHighIndex=swingHighs[h];
      const double swingHighPrice=rates[swingHighIndex].high;

      int breakIndex=-1;
      for(int j=swingHighIndex+1;j<=lastClosed;j++)
        {
         if(rates[j].close>swingHighPrice+breakBuffer)
           {
            breakIndex=j;
            break;
           }
        }
      if(breakIndex<0)
         continue;

      const int swingLowIndex=FindLatestIndexBefore(swingLows,swingHighIndex);
      if(swingLowIndex<0)
         continue;

      const int searchEnd=MathMax(swingLowIndex,breakIndex-InpOrderBlockSearchBars);
      int orderBlockIndex=-1;
      for(int b=breakIndex-1;b>=searchEnd;--b)
        {
         if(rates[b].close<rates[b].open)
           {
            orderBlockIndex=b;
            break;
           }
        }
      if(orderBlockIndex<0)
         continue;

      double rangeHigh=rates[breakIndex].high;
      for(int r=breakIndex;r<=lastClosed;r++)
         rangeHigh=MathMax(rangeHigh,rates[r].high);

      ctx.direction=BIAS_BULL;
      ctx.breakIndex=breakIndex;
      ctx.pivotIndex=swingHighIndex;
      ctx.rangeAnchorIndex=swingLowIndex;
      ctx.orderBlockIndex=orderBlockIndex;
      ctx.rangeLow=rates[swingLowIndex].low;
      ctx.rangeHigh=rangeHigh;
      ctx.midpoint=ctx.rangeLow+((ctx.rangeHigh-ctx.rangeLow)*0.5);
      ctx.obLow=rates[orderBlockIndex].low;
      ctx.obHigh=rates[orderBlockIndex].high;
      ctx.snapshotTime=rates[lastClosed].time;

      if(ctx.rangeHigh>ctx.rangeLow)
         return true;
     }
   return false;
  }

bool FindBearishContext(const MqlRates &rates[],const int lastClosed,const int &swingHighs[],const int &swingLows[],HTFContext &ctx)
  {
   const double point=SymbolPointValue();
   const double breakBuffer=InpBreakBufferPoints*point;

   for(int l=ArraySize(swingLows)-1;l>=0;--l)
     {
      const int swingLowIndex=swingLows[l];
      const double swingLowPrice=rates[swingLowIndex].low;

      int breakIndex=-1;
      for(int j=swingLowIndex+1;j<=lastClosed;j++)
        {
         if(rates[j].close<swingLowPrice-breakBuffer)
           {
            breakIndex=j;
            break;
           }
        }
      if(breakIndex<0)
         continue;

      const int swingHighIndex=FindLatestIndexBefore(swingHighs,swingLowIndex);
      if(swingHighIndex<0)
         continue;

      const int searchEnd=MathMax(swingHighIndex,breakIndex-InpOrderBlockSearchBars);
      int orderBlockIndex=-1;
      for(int b=breakIndex-1;b>=searchEnd;--b)
        {
         if(rates[b].close>rates[b].open)
           {
            orderBlockIndex=b;
            break;
           }
        }
      if(orderBlockIndex<0)
         continue;

      double rangeLow=rates[breakIndex].low;
      for(int r=breakIndex;r<=lastClosed;r++)
         rangeLow=MathMin(rangeLow,rates[r].low);

      ctx.direction=BIAS_BEAR;
      ctx.breakIndex=breakIndex;
      ctx.pivotIndex=swingLowIndex;
      ctx.rangeAnchorIndex=swingHighIndex;
      ctx.orderBlockIndex=orderBlockIndex;
      ctx.rangeLow=rangeLow;
      ctx.rangeHigh=rates[swingHighIndex].high;
      ctx.midpoint=ctx.rangeLow+((ctx.rangeHigh-ctx.rangeLow)*0.5);
      ctx.obLow=rates[orderBlockIndex].low;
      ctx.obHigh=rates[orderBlockIndex].high;
      ctx.snapshotTime=rates[lastClosed].time;

      if(ctx.rangeHigh>ctx.rangeLow)
         return true;
     }
   return false;
  }

bool BuildHTFContext(HTFContext &ctx)
  {
   MqlRates rates[];
   if(!LoadRates(InpHTF,InpHTFLookbackBars+60,rates))
      return false;

   const int n=ArraySize(rates);
   const int lastClosed=n-2;
   if(lastClosed<20)
      return false;

   const int start=MathMax(2,lastClosed-InpHTFLookbackBars);
   const int end=lastClosed-1;
   if(end<=start)
      return false;

   int swingHighs[];
   int swingLows[];
   CollectSwings(rates,start,end,swingHighs,swingLows);
   if(ArraySize(swingHighs)==0 || ArraySize(swingLows)==0)
      return false;

   HTFContext bull;
   HTFContext bear;
   const bool hasBull=FindBullishContext(rates,lastClosed,swingHighs,swingLows,bull);
   const bool hasBear=FindBearishContext(rates,lastClosed,swingHighs,swingLows,bear);

   if(!hasBull && !hasBear)
      return false;
   if(hasBull && !hasBear)
     {
      ctx=bull;
      return true;
     }
   if(!hasBull && hasBear)
     {
      ctx=bear;
      return true;
     }

   ctx=(bull.breakIndex>=bear.breakIndex ? bull : bear);
   return true;
  }

bool BuildLTFBreakerSignal(const HTFContext &context,EntrySignal &signal)
  {
   signal.valid=false;
   signal.direction=context.direction;

   if(context.direction==BIAS_NONE)
      return false;

   MqlRates rates[];
   if(!LoadRates(InpLTF,InpLTFLookbackBars+50,rates))
      return false;

   const int n=ArraySize(rates);
   const int lastClosed=n-2;
   if(lastClosed<10)
      return false;

   const int start=MathMax(3,lastClosed-InpPatternLookbackBars);
   const double point=SymbolPointValue();
   const double sweepBuffer=InpSweepBufferPoints*point;
   const double breakBuffer=InpBreakBufferPoints*point;
   const double stopBuffer=InpStopBufferPoints*point;

   if(context.direction==BIAS_BULL)
     {
      for(int i=lastClosed-3;i>=start;--i)
        {
         if(!IsSwingLow(rates,i))
            continue;

         const double swingLow=rates[i].low;
         int sweepIndex=-1;
         for(int s=i+1;s<=lastClosed-1;s++)
           {
            const bool swept=(rates[s].low<swingLow-sweepBuffer && rates[s].close>swingLow);
            if(!swept)
               continue;
            if(rates[s].low>context.midpoint)
               continue;
            if(InpRequireSweepInsideOB && !CandleTouchesZone(rates[s],context.obLow,context.obHigh))
               continue;
            sweepIndex=s;
            break;
           }
         if(sweepIndex<0)
            continue;
         if(lastClosed-sweepIndex>InpMaxSweepToBreakBars)
            continue;

         double referenceHigh=rates[i].high;
         for(int r=i;r<=sweepIndex;r++)
            referenceHigh=MathMax(referenceHigh,rates[r].high);

         if(rates[lastClosed].close<=referenceHigh+breakBuffer)
            continue;
         if(rates[lastClosed-1].close>referenceHigh+breakBuffer)
            continue;

         double stop=rates[sweepIndex].low;
         for(int z=sweepIndex;z<=lastClosed;z++)
            stop=MathMin(stop,rates[z].low);

         signal.valid=true;
         signal.swingIndex=i;
         signal.sweepIndex=sweepIndex;
         signal.referenceLevel=referenceHigh;
         signal.stopPrice=NormalizePrice(stop-stopBuffer);
         signal.signalTime=rates[lastClosed].time;
         return true;
        }
     }
   else if(context.direction==BIAS_BEAR)
     {
      for(int i=lastClosed-3;i>=start;--i)
        {
         if(!IsSwingHigh(rates,i))
            continue;

         const double swingHigh=rates[i].high;
         int sweepIndex=-1;
         for(int s=i+1;s<=lastClosed-1;s++)
           {
            const bool swept=(rates[s].high>swingHigh+sweepBuffer && rates[s].close<swingHigh);
            if(!swept)
               continue;
            if(rates[s].high<context.midpoint)
               continue;
            if(InpRequireSweepInsideOB && !CandleTouchesZone(rates[s],context.obLow,context.obHigh))
               continue;
            sweepIndex=s;
            break;
           }
         if(sweepIndex<0)
            continue;
         if(lastClosed-sweepIndex>InpMaxSweepToBreakBars)
            continue;

         double referenceLow=rates[i].low;
         for(int r=i;r<=sweepIndex;r++)
            referenceLow=MathMin(referenceLow,rates[r].low);

         if(rates[lastClosed].close>=referenceLow-breakBuffer)
            continue;
         if(rates[lastClosed-1].close<referenceLow-breakBuffer)
            continue;

         double stop=rates[sweepIndex].high;
         for(int z=sweepIndex;z<=lastClosed;z++)
            stop=MathMax(stop,rates[z].high);

         signal.valid=true;
         signal.swingIndex=i;
         signal.sweepIndex=sweepIndex;
         signal.referenceLevel=referenceLow;
         signal.stopPrice=NormalizePrice(stop+stopBuffer);
         signal.signalTime=rates[lastClosed].time;
         return true;
        }
     }

   return false;
  }

double NormalizeVolume(const double volumeRaw)
  {
   const double minVolume=SymbolInfoDouble(g_tradeSymbol,SYMBOL_VOLUME_MIN);
   const double maxVolume=SymbolInfoDouble(g_tradeSymbol,SYMBOL_VOLUME_MAX);
   double volumeStep=SymbolInfoDouble(g_tradeSymbol,SYMBOL_VOLUME_STEP);
   if(volumeStep<=0.0)
      volumeStep=minVolume;

   double v=MathMax(minVolume,MathMin(maxVolume,volumeRaw));
   v=MathFloor(v/volumeStep+1e-9)*volumeStep;
   if(v<minVolume)
      v=minVolume;

   int volumeDigits=2;
   if(volumeStep>0.0)
      volumeDigits=(int)MathMax(0.0,MathRound(-MathLog10(volumeStep)));

   return NormalizeDouble(v,volumeDigits);
  }

double CalculateRiskVolume(const double entryPrice,const double stopPrice)
  {
   const double distance=MathAbs(entryPrice-stopPrice);
   if(distance<=0.0)
      return 0.0;

   const double tickSize=SymbolInfoDouble(g_tradeSymbol,SYMBOL_TRADE_TICK_SIZE);
   const double tickValue=SymbolInfoDouble(g_tradeSymbol,SYMBOL_TRADE_TICK_VALUE);
   if(tickSize<=0.0 || tickValue<=0.0)
      return 0.0;

   const double accountEquity=AccountInfoDouble(ACCOUNT_EQUITY);
   const double riskMoney=accountEquity*(InpRiskPercent/100.0);
   if(riskMoney<=0.0)
      return 0.0;

   const double moneyPerLot=(distance/tickSize)*tickValue;
   if(moneyPerLot<=0.0)
      return 0.0;

   const double rawVolume=riskMoney/moneyPerLot;
   return NormalizeVolume(rawVolume);
  }

double BuildTakeProfit(const int direction,const double entryPrice,const double stopPrice)
  {
   const double risk=MathAbs(entryPrice-stopPrice);
   if(direction==BIAS_BULL)
      return NormalizePrice(entryPrice+(risk*InpRewardRisk));
   if(direction==BIAS_BEAR)
      return NormalizePrice(entryPrice-(risk*InpRewardRisk));
   return 0.0;
  }

bool HasManagedPosition()
  {
   for(int i=PositionsTotal()-1;i>=0;--i)
     {
      const ulong ticket=PositionGetTicket(i);
      if(ticket==0)
         continue;
      if(PositionGetString(POSITION_SYMBOL)!=g_tradeSymbol)
         continue;
      if((long)PositionGetInteger(POSITION_MAGIC)!=InpMagicNumber)
         continue;
      return true;
     }
   return false;
  }

void GetTodayStats(int &closedTrades,double &closedPnL)
  {
   closedTrades=0;
   closedPnL=0.0;

   datetime now=TimeTradeServer();
   if(now<=0)
      now=TimeCurrent();

   MqlDateTime dt;
   TimeToStruct(now,dt);
   dt.hour=0;
   dt.min=0;
   dt.sec=0;
   const datetime dayStart=StructToTime(dt);

   if(!HistorySelect(dayStart,now))
      return;

   const int totalDeals=(int)HistoryDealsTotal();
   for(int i=0;i<totalDeals;i++)
     {
      const ulong dealTicket=HistoryDealGetTicket(i);
      if(dealTicket==0)
         continue;
      if(HistoryDealGetString(dealTicket,DEAL_SYMBOL)!=g_tradeSymbol)
         continue;
      if((long)HistoryDealGetInteger(dealTicket,DEAL_MAGIC)!=InpMagicNumber)
         continue;

      const long entry=(long)HistoryDealGetInteger(dealTicket,DEAL_ENTRY);
      if(entry!=DEAL_ENTRY_OUT && entry!=DEAL_ENTRY_OUT_BY)
         continue;

      const double dealPnL=
         HistoryDealGetDouble(dealTicket,DEAL_PROFIT)+
         HistoryDealGetDouble(dealTicket,DEAL_SWAP)+
         HistoryDealGetDouble(dealTicket,DEAL_COMMISSION);

      closedPnL+=dealPnL;
      closedTrades++;
     }
  }

bool PassesDailyGuards()
  {
   int todayTrades=0;
   double todayPnL=0.0;
   GetTodayStats(todayTrades,todayPnL);

   if(InpMaxTradesPerDay>0 && todayTrades>=InpMaxTradesPerDay)
      return false;

   if(InpMaxDailyLossPercent>0.0)
     {
      const double estimatedStartBalance=AccountInfoDouble(ACCOUNT_BALANCE)-todayPnL;
      if(estimatedStartBalance>0.0)
        {
         const double maxLossMoney=estimatedStartBalance*(InpMaxDailyLossPercent/100.0);
         if(todayPnL<=-maxLossMoney)
            return false;
        }
     }

   return true;
  }

bool IsSessionOpen()
  {
   if(!InpUseSessionFilter)
      return true;

   datetime now=TimeTradeServer();
   if(now<=0)
      now=TimeCurrent();

   MqlDateTime dt;
   TimeToStruct(now,dt);
   const int hour=dt.hour;

   if(InpSessionStartHour==InpSessionEndHour)
      return true;

   if(InpSessionStartHour<InpSessionEndHour)
      return (hour>=InpSessionStartHour && hour<InpSessionEndHour);

   return (hour>=InpSessionStartHour || hour<InpSessionEndHour);
  }

bool IsSpreadAcceptable(const MqlTick &tick)
  {
   if(InpMaxSpreadPoints<=0)
      return true;

   const double point=SymbolPointValue();
   if(point<=0.0)
      return false;

   const int spreadPoints=(int)MathRound((tick.ask-tick.bid)/point);
   return (spreadPoints<=InpMaxSpreadPoints);
  }

bool IsNewLTFBar()
  {
   const datetime barTime=iTime(g_tradeSymbol,InpLTF,0);
   if(barTime<=0)
      return false;
   if(barTime==g_lastProcessedLTFBar)
      return false;
   g_lastProcessedLTFBar=barTime;
   return true;
  }

void ManageOpenPositions(const MqlTick &tick)
  {
   if(InpBreakEvenAtR<=0.0)
      return;

   const double point=SymbolPointValue();
   const double stopsLevel=((double)SymbolInfoInteger(g_tradeSymbol,SYMBOL_TRADE_STOPS_LEVEL))*point;

   for(int i=PositionsTotal()-1;i>=0;--i)
     {
      const ulong ticket=PositionGetTicket(i);
      if(ticket==0)
         continue;
      if(PositionGetString(POSITION_SYMBOL)!=g_tradeSymbol)
         continue;
      if((long)PositionGetInteger(POSITION_MAGIC)!=InpMagicNumber)
         continue;

      const long type=(long)PositionGetInteger(POSITION_TYPE);
      const double openPrice=PositionGetDouble(POSITION_PRICE_OPEN);
      const double sl=PositionGetDouble(POSITION_SL);
      const double tp=PositionGetDouble(POSITION_TP);

      if(type==POSITION_TYPE_BUY)
        {
         if(sl<=0.0 || sl>=openPrice)
            continue;

         const double risk=openPrice-sl;
         const double reward=tick.bid-openPrice;
         if(risk<=0.0 || reward<risk*InpBreakEvenAtR)
            continue;

         double newSL=openPrice+(InpBreakEvenLockPoints*point);
         if(newSL>tick.bid-stopsLevel)
            newSL=tick.bid-stopsLevel;
         if(newSL<=sl)
            continue;

         g_trade.PositionModify(g_tradeSymbol,NormalizePrice(newSL),tp);
        }
      else if(type==POSITION_TYPE_SELL)
        {
         if(sl<=0.0 || sl<=openPrice)
            continue;

         const double risk=sl-openPrice;
         const double reward=openPrice-tick.ask;
         if(risk<=0.0 || reward<risk*InpBreakEvenAtR)
            continue;

         double newSL=openPrice-(InpBreakEvenLockPoints*point);
         if(newSL<tick.ask+stopsLevel)
            newSL=tick.ask+stopsLevel;
         if(newSL>=sl)
            continue;

         g_trade.PositionModify(g_tradeSymbol,NormalizePrice(newSL),tp);
        }
     }
  }

bool ExecuteEntry(const HTFContext &context,const EntrySignal &signal,const MqlTick &tick)
  {
   double entryPrice=(signal.direction==BIAS_BULL ? tick.ask : tick.bid);
   double stopPrice=signal.stopPrice;
   if(entryPrice<=0.0 || stopPrice<=0.0)
      return false;

   const double point=SymbolPointValue();
   const double minStops=((double)SymbolInfoInteger(g_tradeSymbol,SYMBOL_TRADE_STOPS_LEVEL))*point+point;

   if(signal.direction==BIAS_BULL)
     {
      if(entryPrice<=stopPrice)
         return false;
      if((entryPrice-stopPrice)<minStops)
         stopPrice=entryPrice-minStops;
     }
   else if(signal.direction==BIAS_BEAR)
     {
      if(entryPrice>=stopPrice)
         return false;
      if((stopPrice-entryPrice)<minStops)
         stopPrice=entryPrice+minStops;
     }
   else
      return false;

   const double volume=CalculateRiskVolume(entryPrice,stopPrice);
   if(volume<=0.0)
      return false;

   const double tp=BuildTakeProfit(signal.direction,entryPrice,stopPrice);
   stopPrice=NormalizePrice(stopPrice);

   g_trade.SetExpertMagicNumber(InpMagicNumber);
   g_trade.SetDeviationInPoints(InpMaxSlippagePoints);

   bool orderSent=false;
   ResetLastError();
   if(signal.direction==BIAS_BULL)
      orderSent=g_trade.Buy(volume,g_tradeSymbol,0.0,stopPrice,tp,"GBreaker");
   else
      orderSent=g_trade.Sell(volume,g_tradeSymbol,0.0,stopPrice,tp,"GBreaker");

   if(!orderSent)
     {
      PrintFormat("Order rejected. Retcode=%d (%s), err=%d",
                  (int)g_trade.ResultRetcode(),
                  g_trade.ResultRetcodeDescription(),
                  GetLastError());
      return false;
     }

   PrintFormat("Entry placed: dir=%d vol=%.2f entry=%.2f sl=%.2f tp=%.2f htfBreakIdx=%d",
               signal.direction,volume,entryPrice,stopPrice,tp,context.breakIndex);
   return true;
  }

int OnInit()
  {
   g_tradeSymbol=InpSymbol;
   StringTrimLeft(g_tradeSymbol);
   StringTrimRight(g_tradeSymbol);
   if(StringLen(g_tradeSymbol)==0)
      g_tradeSymbol=_Symbol;

   if(!SymbolSelect(g_tradeSymbol,true))
     {
      if(g_tradeSymbol!=_Symbol && SymbolSelect(_Symbol,true))
         g_tradeSymbol=_Symbol;
      else
        {
         Print("Failed to select symbol: ",g_tradeSymbol);
         return INIT_FAILED;
        }
     }

   g_trade.SetExpertMagicNumber(InpMagicNumber);
   g_trade.SetDeviationInPoints(InpMaxSlippagePoints);

   PrintFormat("ICT_Gold_Breaker_EA initialized on %s (requested=%s, server=%s, HTF=%s LTF=%s)",
               g_tradeSymbol,
               (StringLen(InpSymbol)>0 ? InpSymbol : "chart_symbol"),
               AccountInfoString(ACCOUNT_SERVER),
               EnumToString(InpHTF),
               EnumToString(InpLTF));
   return INIT_SUCCEEDED;
  }

void OnTick()
  {
   MqlTick tick;
   if(!SymbolInfoTick(g_tradeSymbol,tick))
      return;

   ManageOpenPositions(tick);

   if(!IsNewLTFBar())
      return;

   if(InpAllowSinglePositionOnly && HasManagedPosition())
      return;
   if(!IsSessionOpen())
      return;
   if(!IsSpreadAcceptable(tick))
      return;
   if(!PassesDailyGuards())
      return;

   HTFContext context;
   if(!BuildHTFContext(context))
      return;

   EntrySignal signal;
   if(!BuildLTFBreakerSignal(context,signal))
      return;
   if(!signal.valid)
      return;
   if(signal.signalTime==g_lastExecutedSignal)
      return;

   if(ExecuteEntry(context,signal,tick))
      g_lastExecutedSignal=signal.signalTime;
  }
